name: checkout
on: 
  push:
    branches:
      - main
jobs:
 checkout-job:
    runs-on: ubuntu-latest
    steps:
      - name:  display current file name
        run: ls -lrt
      - uses: checkout@v3
      - name: checkout after
        run: ls -lrt