name: ciworkflow
on:
  push:
    branches:
      - main

jobs:
  run-shell-commands:
    runs-on: ubuntu-latest
    steps:
      - name: Echo a string
        run: echo "Hello, world"
      - name: Multiline command
        run: |
          node -v
          npm -v

  parallel-jobs-macos:
    runs-on: macos-latest
    steps:
      - name: View macOS version
        run: sw_vers

  dependency-jobs:
    runs-on: windows-latest
    needs: run-shell-commands
    steps:
      - name: Echo a string
        run: Write-Host "Hello, world"
      - name: Placeholder for error step
        run: echo "This step needs a valid commandss"
