name: event
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs: 
  event-job: 
    runs-on: ubuntu-latest
    steps: 
    - run: |
      echo $GITHUB_SHA
      echo $GITHUB_REF
    - uses: actions/checkout@v2
