name: pull request comment
on: 
  pull_request_target:
    types: [opened]
jobs: 
    pr-comments: 
      runs-on: ubuntu-latest
      steps: 
        - name: comment one new prs
          uses: actions/github-script@v6
          with: 
            script: |
              github.rest.issues.createComment({
                issue_number: github.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: 'Thanks for opening this PR!',
              });