name: pull request comment
on: 
  pull_request_target:
    types: [opened]
jobs: 
    pr-comments: 
      runs-on: ubuntu-latest
      steps: 
        - name: comment one new prs
          uses: actions/github-script@v6
          script: |
              github.rest.issues.createComment({
                issue_number: github.event.pull_request.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: 'Thanks for opening this PR!'
              })'