name: Workflow Run
on:
  workflow_run:
    workflows: [Repository Event]
    types: [completed]
    branches: 
      - main
jobs: 
    echo-strings:
        runs-on: ubuntu-latest
        steps: 
            - run: echo " hello i was triggered 'repository event" completed
